[build]
builder = "NIXPACKS"

[deploy]
startCommand = "uvicorn app:app --host 0.0.0.0 --port 8000"

[[services]]
[services.cron]
startCommand = "python daily_aggregator.py"
cronSchedule = "0 1 * * *"  # Run daily at 1 AM UTC
