[build]
builder = "NIXPACKS"

[deploy]
startCommand = "uvicorn app:app --host 0.0.0.0 --port 8000 --timeout-keep-alive 30"

# Main web service configuration
[[services]]
name = "web"
startCommand = "uvicorn app:app --host 0.0.0.0 --port 8000 --timeout-keep-alive 30"

# Cron service configuration
[[services]]
name = "cron"
startCommand = "python cron_daily_aggregator.py"
cronSchedule = "0 0 * * *"
